<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_No data to display_ctl00_MainContent_AP_beb17f</name>
   <tag></tag>
   <elementGuidId>a4dbd6b4-413d-4a33-a002-eadd8567a812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-vam</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Cancel_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/API/iframe_AP Invoice_undefined_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Delete'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Delete' and @src = '../../Content/Images/Cancel_16x16.png?1=1' and @alt = 'Delete' and @id = 'ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXCBtn0Img']</value>
   </webElementXpaths>
</WebElementEntity>
