<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_ctl00MainContentAPJournalEntr_c0326a</name>
   <tag></tag>
   <elementGuidId>fbd6b973-9d96-4421-b866-d27e8af712d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$APJournalEntryDtl$cbpAPJournalEntry$cpnlAPJEItem$formAPJEItem$PC_0$gvAPJEItem$DXEditor3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/API/iframe_AP Invoice_undefined_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3']/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table[2]/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_APJournalEntryDtl_cbpAPJournalEntry_cpnlAPJEItem_formAPJEItem_PC_0_gvAPJEItem_DXEditor3_I' and @name = 'ctl00$MainContent$APJournalEntryDtl$cbpAPJournalEntry$cpnlAPJEItem$formAPJEItem$PC_0$gvAPJEItem$DXEditor3' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
