<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Outstanding_ctl00_MainContent_APPayment_94c6a7</name>
   <tag></tag>
   <elementGuidId>82bb1842-9d8e-49fa-b528-e4e0f7661065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxIcon_actions_converttorange_16x16 dx-vam</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-xoLhl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APP/iframe_AP Payment_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApply']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/DXR.axd?r=1_110-xoLhl' and @id = 'ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_cbpAPPaymentDtl2_formAPPaymentDtl2_gvKnockOffItem_header14_btnAutoApplyImg']</value>
   </webElementXpaths>
</WebElementEntity>
