<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SHOPEE_ctl00MainContentAPPaymentDtlcb_83b2ea</name>
   <tag></tag>
   <elementGuidId>5d6f8326-1be6-451d-922c-acdbd47dcd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$APPaymentDtl$cbpAPJournalEntry$cpnlAPPItem$formAPJEItem$PC_0$ASPxFormLayout3$gvAPPItemNew$DXEditor7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APP/iframe_AP Payment_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7']/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_APPaymentDtl_cbpAPJournalEntry_cpnlAPPItem_formAPJEItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor7_I' and @name = 'ctl00$MainContent$APPaymentDtl$cbpAPJournalEntry$cpnlAPPItem$formAPJEItem$PC_0$ASPxFormLayout3$gvAPPItemNew$DXEditor7' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
