<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Additional Header Info_ctl00_MainConten_776c4c</name>
   <tag></tag>
   <elementGuidId>d60de58a-fe3b-45d3-ae2e-a68613e438d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click Here Or Press [Insert] To Add Record</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeImage_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ASPx.SEClick('ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add', event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Add_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARP/iframe_AR Payment_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_tcheader0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Click Here Or Press [Insert] To Add Record'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Click Here Or Press [Insert] To Add Record' and @id = 'ctl00_MainContent_ARPaymentDtl_cbpARPayment_cpnlARPaymentItem_formARPaymentItem_PC_0_ASPxFormLayout3_gvARItemNew_header0_Add' and @src = '../../Content/Images/Add_16x16.png?1=1']</value>
   </webElementXpaths>
</WebElementEntity>
