<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Additional Notes_ctl00_MainContent_Purc_d2f4de</name>
   <tag></tag>
   <elementGuidId>3e5c3489-eedc-495b-922c-baf21aa5e1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Search_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/purchase invoice/iframe_Purchase Invoice_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_PurchaseInvoiceDetail1_cbpPurchaseInvoice_cbpPIDetails_formPIDetails_PC_0_ItemAdvanceSearchControlGRDetail_txtItemSearchUpdate_B0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
