<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading_ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img</name>
   <tag></tag>
   <elementGuidId>09e2d875-0a96-493f-a9cb-8f4b2d7743d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-AJMSh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/ST/iframe_Stock Transfer_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_InventoryTransferDetail1_cbpInventoryTransferDetails_ASPxRoundPanel1_formInventoryTransfer_cbFromWarehouse_cbWarehouse_B-1']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/img</value>
   </webElementXpaths>
</WebElementEntity>
