<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Item_ctl00_MainContent_ReportFrameWork_42edfd</name>
   <tag></tag>
   <elementGuidId>a6cca925-a1a5-448d-bfed-94089cfa1a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxWeb_edtCheckBoxUnchecked_iOS dxICheckBox_iOS dxichSys dx-not-acc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/RPT/IV/iframe_Stock Card_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXDataRow0']/td/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[2]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[6]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY PIN'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BISKUT PLANTA'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/table/tbody/tr/td[4]/div/div/div/div/table/tbody/tr/td/table/tbody/tr[2]/td/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_ReportFrameWorkInventory_cbpReport_cbpReportFrameworkParameter_rpReportFramework_formReportFrameworkParameter_cbItem_glItem_DDD_gv_DXSelBtn0_D']</value>
   </webElementXpaths>
</WebElementEntity>
