<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AR Invoice Document Report_0</name>
   <tag></tag>
   <elementGuidId>492b65fe-3791-4697-8112-a4e3860333db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>CloseJqueryLoadingPanel();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sit-report.irsalaya.com/Modules/Report/m_ReportViewerFR1.aspx?EncData=er+TpnHl/nAHC+LbNMYSxxcsdpDMSIqUb4LHKJXjlzndPsWWP3gt9H5PzDvz1tVWl5/bPv+5EYsf/bJa6aStEaqEqMKPTasnssDd60W3fpA263KKi4kTqQaCNsOKQx08JQb/IJgBW+xibBSiVEuR3v54XqjAJkuzh6VA/E3hg11deNzcFfxG6XYLuWHB5yp2lk4PRwMWL3caPIyLeuj9YJp7zlx6ZllGDrs6nSR7cpRvVOEMDmBqqzZu7sZlklrnXnQ2unrODm9uCer6t5uv+1xOysR7IcDbD8Zp4xf1XfzcOBsJgfbDLnOG4ezAGgb7YMDHXbFStxZHyofTFuhhBGSoDOk4enIyFYWnyKRklJXlEsVnM6Ikb6/LnW+V7OTUL9ne+JOruGa1HaZEi/mk4A==</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabframe_0']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '0' and @id = '0' and @src = 'https://sit-report.irsalaya.com/Modules/Report/m_ReportViewerFR1.aspx?EncData=er+TpnHl/nAHC+LbNMYSxxcsdpDMSIqUb4LHKJXjlzndPsWWP3gt9H5PzDvz1tVWl5/bPv+5EYsf/bJa6aStEaqEqMKPTasnssDd60W3fpA263KKi4kTqQaCNsOKQx08JQb/IJgBW+xibBSiVEuR3v54XqjAJkuzh6VA/E3hg11deNzcFfxG6XYLuWHB5yp2lk4PRwMWL3caPIyLeuj9YJp7zlx6ZllGDrs6nSR7cpRvVOEMDmBqqzZu7sZlklrnXnQ2unrODm9uCer6t5uv+1xOysR7IcDbD8Zp4xf1XfzcOBsJgfbDLnOG4ezAGgb7YMDHXbFStxZHyofTFuhhBGSoDOk4enIyFYWnyKRklJXlEsVnM6Ikb6/LnW+V7OTUL9ne+JOruGa1HaZEi/mk4A==']</value>
   </webElementXpaths>
</WebElementEntity>
