<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cancel_ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll</name>
   <tag></tag>
   <elementGuidId>63fc78da-53fa-4516-bdfb-5e89347be18e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click Here Or Press [Insert] To Add Record</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeImage_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ASPx.SEClick('ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll', event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Add_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARI/iframe_AR Invoice_58</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_tcheader17']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Click Here Or Press [Insert] To Add Record']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Click Here Or Press [Insert] To Add Record' and @id = 'ctl00_MainContent_ARJournalEntryHDR_cpnlARJEHeader_formC_gvARJournalEntry_header17_btnCheckAll' and @src = '../../Content/Images/Add_16x16.png?1=1']</value>
   </webElementXpaths>
</WebElementEntity>
