<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_ctl00MainContentARJournalEntryDTLcbpARJournalEntrycbpARJournalEntryDetailASPxRoundPanel1formARJEHeadercbCustomercbSelectCust</name>
   <tag></tag>
   <elementGuidId>0f4344e5-a553-4c27-98cb-4703b2222321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ARJournalEntryDTL$cbpARJournalEntry$cbpARJournalEntryDetail$ASPxRoundPanel1$formARJEHeader$cbCustomer$cbSelectCust</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Customer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARI/iframe_AR Invoice_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust']/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_ARJournalEntryDTL_cbpARJournalEntry_cbpARJournalEntryDetail_ASPxRoundPanel1_formARJEHeader_cbCustomer_cbSelectCust_I' and @name = 'ctl00$MainContent$ARJournalEntryDTL$cbpARJournalEntry$cbpARJournalEntryDetail$ASPxRoundPanel1$formARJEHeader$cbCustomer$cbSelectCust' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
