<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Additional Notes_ctl00_MainContent_Stoc_0b0e2a</name>
   <tag></tag>
   <elementGuidId>c7d65560-a492-4f13-9bd9-6d17d0cb4243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Search_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/SI/iframe_Stock Issue_undefined_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_StockIssueDetail_cbpStockIssueDetails_cpnlSIDetail_formSIDetail_PC_0_ItemAdvanceSearchControlSIDetail_txtItemSearchUpdate_B0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
