<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_ctl00MainContentAPCreditN_c01a82</name>
   <tag></tag>
   <elementGuidId>64a7a65d-8732-4245-9bb1-951aa1147a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$APCreditNoteDtl$cbpAPCreditNote$cpnlAPPItem$formAPCNItem$PC_0$ASPxFormLayout3$gvAPPItemNew$DXEditor9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APCN/iframe_AP Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9']/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div[2]/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor9_I' and @name = 'ctl00$MainContent$APCreditNoteDtl$cbpAPCreditNote$cpnlAPPItem$formAPCNItem$PC_0$ASPxFormLayout3$gvAPPItemNew$DXEditor9' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
