<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00MainContentAPCreditNoteDtlcbpAP_a16ea8</name>
   <tag></tag>
   <elementGuidId>1d2274f4-93b6-4150-89a2-578579ca4a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$APCreditNoteDtl$cbpAPCreditNote$cbpAPCreditNoteDetail$ASPxRoundPanel1$formAPCNHeader$txtDescription</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APCN/iframe_AP Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription']/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_txtDescription_I' and @name = 'ctl00$MainContent$APCreditNoteDtl$cbpAPCreditNote$cbpAPCreditNoteDetail$ASPxRoundPanel1$formAPCNHeader$txtDescription' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
