<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_GST-3030</name>
   <tag></tag>
   <elementGuidId>93da036a-2b4c-4169-9220-a3c7ca924c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_iOS dxeFTM dxeListBoxItemHover_iOS dxeListBoxItemSelected_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GST-3030</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APCN/iframe_AP Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBT']/tr[3]/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESIDUAL INPUT TAX'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GST-3020'])[1]/following::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP (CREDITOR) BAD DEBT RELIEF/RECOVERY'])[1]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GST-3040'])[1]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GST-3030']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tr[3]/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_DDD_L_LBI2T0' and (text() = 'GST-3030' or . = 'GST-3030')]</value>
   </webElementXpaths>
</WebElementEntity>
