<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Loading_ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1</name>
   <tag></tag>
   <elementGuidId>a38719dc-898d-454e-a9d5-9f3dbd266b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeButton dxeButtonEditButton_iOS dxeButtonEditButtonHover_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ASPx.BEClick('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor',1)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APCN/iframe_AP Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor']/tbody/tr/td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[4]/following::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor:'])[1]/following::td[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No.'])[1]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cbpAPCreditNoteDetail_ASPxRoundPanel1_formAPCNHeader_cbVendor_cbVendor_B1']</value>
   </webElementXpaths>
</WebElementEntity>
