<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Loading_ctl00_MainContent_APCreditNoteDt_2c46a6</name>
   <tag></tag>
   <elementGuidId>7481a1ad-9587-4096-81c7-fcd8f05560a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeButton dxeButtonEditButton_iOS dxeButtonEditButtonHover_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return ASPx.DDDropDown('ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3', event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APCN/iframe_AP Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3']/tbody/tr/td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[14]/following::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data to display'])[3]/following::td[24]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No.'])[3]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[3]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table[2]/tbody/tr/td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'ctl00_MainContent_APCreditNoteDtl_cbpAPCreditNote_cpnlAPPItem_formAPCNItem_PC_0_ASPxFormLayout3_gvAPPItemNew_DXEditor3_B-1']</value>
   </webElementXpaths>
</WebElementEntity>
