<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AR Invoice_undefined</name>
   <tag></tag>
   <elementGuidId>708c04a0-1fc3-4e78-9333-060321279117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabframe_58 > #undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='undefined'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>CloseJqueryLoadingPanel();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Modules/AR/m_ARJournalEntryDtl.aspx?EncData=e4U0ZH2X7FAE6NE2X0gEqJoIRjDDoZ9Nsf2b/vQIp9xyqmVVKwb8gyMPiZnMliGK74/isaOq6Z1Zqw9k+ObfVMzLHs5jz+6TBgc7Agb4U6ukwADErWbf4EsRT92M1D442+Lh6CeWnZEvUHZ7QZm09Ns7UUKqRbU5ZRMUqmlxzrRNPAZwAeLrjtH6FMf/emuoacerkT4wde63riV4ytgsshn88xabK/s+xeGoM6t8o7Y=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabframe_58&quot;)/iframe[@id=&quot;undefined&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='undefined'])</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabframe_58']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'undefined' and @id = 'undefined' and @src = '/Modules/AR/m_ARJournalEntryDtl.aspx?EncData=e4U0ZH2X7FAE6NE2X0gEqJoIRjDDoZ9Nsf2b/vQIp9xyqmVVKwb8gyMPiZnMliGK74/isaOq6Z1Zqw9k+ObfVMzLHs5jz+6TBgc7Agb4U6ukwADErWbf4EsRT92M1D442+Lh6CeWnZEvUHZ7QZm09Ns7UUKqRbU5ZRMUqmlxzrRNPAZwAeLrjtH6FMf/emuoacerkT4wde63riV4ytgsshn88xabK/s+xeGoM6t8o7Y=']</value>
   </webElementXpaths>
</WebElementEntity>
