<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Currency_ctl00_MainContent_ARContraDtl__409307</name>
   <tag></tag>
   <elementGuidId>6c6ec143-a84a-484e-9aa3-03334cf20ac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxIcon_actions_converttorange_16x16 dx-vam</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-xoLhl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARC/iframe_AR Contra_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApply']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/DXR.axd?r=1_110-xoLhl' and @id = 'ctl00_MainContent_ARContraDtl_cbpARContra_cpnlARPItem_formARCNItem_PC_0_cbpARPaymentDtl2_formARPaymentDtl2_gvContraKnockOffItem2_header12_btnAutoApplyImg']</value>
   </webElementXpaths>
</WebElementEntity>
