<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contra Amount_ctl00MainContentARContr_10a9b8</name>
   <tag></tag>
   <elementGuidId>e4342657-5f5b-4f28-8fcb-8951b6cfbb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ARContraDtl$cbpARContra$cbpARContraDetail$ASPxRoundPanel1$formARCNHeader$txtContraAmount</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARC/iframe_AR Contra_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount']/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_ARContraDtl_cbpARContra_cbpARContraDetail_ASPxRoundPanel1_formARCNHeader_txtContraAmount_I' and @name = 'ctl00$MainContent$ARContraDtl$cbpARContra$cbpARContraDetail$ASPxRoundPanel1$formARCNHeader$txtContraAmount' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
