<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_STORE</name>
   <tag></tag>
   <elementGuidId>fe153a09-c909-49aa-9cd5-0d8c1116761b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1' and (text() = 'STORE' or . = 'STORE') and @ref_element = 'Object Repository/Deployment test/STR/iframe_Stock Transfer Request_undefined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_iOS dxeLTM dxeListBoxItemHover_iOS dxeListBoxItemSelected_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STORE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/STR/iframe_Stock Transfer Request_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBI4T1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_InventoryTransferRequestDetail1_cbpInventoryTransferRequestDetails_ASPxRoundPanel1_formInventoryTransferRequest_cbToWarehouse_cbWarehouse_DDD_L_LBT']/tr[5]/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STORE'])[3]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST18'])[4]/following::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAMBUN'])[3]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAMBUN'])[4]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table[2]/tbody/tr/td/div[2]/div/div/div/table/tbody/tr/td/div[2]/div/table[2]/tr[5]/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
