<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading_ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img</name>
   <tag></tag>
   <elementGuidId>f7bc48e4-c0d7-44a1-921c-7bc36a22aa80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Search_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AR/ARCN/iframe_AR Credit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_MainContent_ARCreditNoteDtl_cbpARCreditNote_cbpARCreditNoteDetail_ASPxRoundPanel1_formARCNHeader_cbCustomer_cbSelectCust_B1Img' and @src = '../../Content/Images/Search_16x16.png?1=1' and @alt = '...']</value>
   </webElementXpaths>
</WebElementEntity>
