<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00MainContentAPDebitNoteDtlcbpAPD_b6b9a7</name>
   <tag></tag>
   <elementGuidId>a8b54c51-2078-47ef-bef4-39e970480cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_iOS dxeEditAreaSys dxh0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$APDebitNoteDtl$cbpAPDebitNote$cbpAPDebitNoteDetail$ASPxRoundPanel1$formAPDNHeader$txtSupplierDebitNoteNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/AP/APDN/iframe_AP Debit Note_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo']/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_APDebitNoteDtl_cbpAPDebitNote_cbpAPDebitNoteDetail_ASPxRoundPanel1_formAPDNHeader_txtSupplierDebitNoteNo_I' and @name = 'ctl00$MainContent$APDebitNoteDtl$cbpAPDebitNote$cbpAPDebitNoteDetail$ASPxRoundPanel1$formAPDNHeader$txtSupplierDebitNoteNo' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
