<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Name_dxWeb_pcCloseButton_iOS</name>
   <tag></tag>
   <elementGuidId>40343dfa-183b-4c82-85a5-7f920fc8bb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbVendor_gsc_cbVendor_pcGeneralSearchControl_HCB-1 > img.dxWeb_pcCloseButton_iOS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbVendor_gsc_cbVendor_pcGeneralSearchControl_HCB-1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxWeb_pcCloseButton_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-xoLhl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbVendor_gsc_cbVendor_pcGeneralSearchControl_HCB-1&quot;)/img[@class=&quot;dxWeb_pcCloseButton_iOS&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/goods receive/iframe_Goods Receive_undefined_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbVendor_gsc_cbVendor_pcGeneralSearchControl_HCB-1']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/div[3]/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
