<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading_ctl00_MainContent_PurchaseGoodR_e480cc</name>
   <tag></tag>
   <elementGuidId>e58c61db-dd4d-4cb4-a226-814e4c9c9609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-xoLhl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/goods receive/iframe_Goods Receive_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_PurchaseGoodReceiveDetail1_cbpPurchaseGoodReceive_cbpPGRHeader_ASPxRoundPanel1_formPGRHeader_cbSelectWareHouse_cbWarehouse_B-1']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/table[2]/tbody/tr/td[4]/img</value>
   </webElementXpaths>
</WebElementEntity>
