<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Customer Aging_undefined</name>
   <tag></tag>
   <elementGuidId>c5027539-998a-46a0-8db1-53b9d2c3297f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='undefined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>CloseJqueryLoadingPanel();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Modules/Report/m_ReportFrameWork.aspx?EncData=NC7O+DRpq5iYcuBnCwhvoJGifMgVAqTJMa5BTDT6IL+by2Ef7Z7V5GRQ8lBr4R33L0BVQyNjkWfCmhJoGbvFmzbFM28+hSLrzUqq8+e3Xv3XVHpktwdsUeeatd0d4vNY75oRObLRBU1LqFNoZpzPmSl30bZnfzZtEFvmmggdKGzYCgPmwAKuR/k27ZNpZOtm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='undefined']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabframe_undefined']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'undefined' and @id = 'undefined' and @src = '/Modules/Report/m_ReportFrameWork.aspx?EncData=NC7O+DRpq5iYcuBnCwhvoJGifMgVAqTJMa5BTDT6IL+by2Ef7Z7V5GRQ8lBr4R33L0BVQyNjkWfCmhJoGbvFmzbFM28+hSLrzUqq8+e3Xv3XVHpktwdsUeeatd0d4vNY75oRObLRBU1LqFNoZpzPmSl30bZnfzZtEFvmmggdKGzYCgPmwAKuR/k27ZNpZOtm']</value>
   </webElementXpaths>
</WebElementEntity>
