<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OK_ctl00_MainContent_StockReceiveDetail_30c0fe</name>
   <tag></tag>
   <elementGuidId>c78ebae7-dc1d-4844-a983-68913e91dc44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0Img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Content/Images/Search_16x16.png?1=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0Img&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/SR2/iframe_Stock Receive_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0Img']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_StockReceiveDetail_cbpStockReceiveDetails_cpnlSRDetail_formSRDetail_PC_0_ItemAdvanceSearchControlSRDetail_txtItemSearchUpdate_B0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
