<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Stock Transfer Request Summary Report_0</name>
   <tag></tag>
   <elementGuidId>a044bfcc-dfdd-49ee-b030-d305e4f10e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>CloseJqueryLoadingPanel();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sit-report.irsalaya.com/Modules/Report/m_ReportViewerFR1.aspx?EncData=er+TpnHl/nAHC+LbNMYSxxcsdpDMSIqUb4LHKJXjlzmtdYaRynH340Dvbr5h2ksmEPknWwWCm84tlcYbYSPH4fEdskN/rGGyWu8iVmN49FzoIx7ibf0Adl0m3Co20Q0Tzdcl9CBtbD6P0t0hGZbJZNZLvgpSQtJ5o+EE5r8NxzrSJcWswE+DiTol0v8lQuC/vF+8JcZn+bVCk+fiNniyl7eCVzAXmihlR1HP901R6vf3miD1e3ydbd86bL9TtNBSCsTnU8xTb/Gylv03P938iUDU7DdXx0s8traCIg52MFW3W/8NSZff278DTa9j9Bhvo/hqFlabqbV7J9NHE/o/y7XUnY+cWMuIRUjH2plA44b1wcpgS9t6yDzcnnsfw+Y8Ixjq+9lFBV/gWfV0qqCG23o+rzUgKpdAE4aiyzQIYSo=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabframe_0']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/iframe</value>
   </webElementXpaths>
</WebElementEntity>
