<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Warehouse_dxgvCommandColumn_iOS dx-nowra_94c735</name>
   <tag></tag>
   <elementGuidId>9d7d385a-cac5-42e0-91c3-c4fe374aec8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;ASPx.GVScheduleCommand('ctl00_MainContent_PurchaseGoodReturnDetail1_cbpPurchaseGoodReturn_TransferFrom_pcTransferFrom_cpnlTransferFrom_formTransferFrom_PC_0_gvTransferFrom',['Select',0],1,event)&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.dxgvCommandColumn_iOS.dx-nowrap.dxgv.dx-ac</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgvCommandColumn_iOS dx-nowrap dxgv dx-ac</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ASPx.GVScheduleCommand('ctl00_MainContent_PurchaseGoodReturnDetail1_cbpPurchaseGoodReturn_TransferFrom_pcTransferFrom_cpnlTransferFrom_formTransferFrom_PC_0_gvTransferFrom',['Select',0],1,event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_PurchaseGoodReturnDetail1_cbpPurchaseGoodReturn_TransferFrom_pcTransferFrom_cpnlTransferFrom_formTransferFrom_PC_0_gvTransferFrom_DXDataRow0&quot;)/td[@class=&quot;dxgvCommandColumn_iOS dx-nowrap dxgv dx-ac&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/Goods Return Post/iframe_Goods Return_undefined</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;ASPx.GVScheduleCommand('ctl00_MainContent_PurchaseGoodReturnDetail1_cbpPurchaseGoodReturn_TransferFrom_pcTransferFrom_cpnlTransferFrom_formTransferFrom_PC_0_gvTransferFrom',['Select',0],1,event)&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_MainContent_PurchaseGoodReturnDetail1_cbpPurchaseGoodReturn_TransferFrom_pcTransferFrom_cpnlTransferFrom_formTransferFrom_PC_0_gvTransferFrom_DXDataRow0']/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/following::td[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::td[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GR-00004733'])[1]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test123'])[1]/preceding::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td</value>
   </webElementXpaths>
</WebElementEntity>
