<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_KLEBANG</name>
   <tag></tag>
   <elementGuidId>460970fa-01de-4d10-adcb-642ba2286fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBI2T1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBI2T1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_iOS dxeLTM dxeListBoxItemHover_iOS dxeListBoxItemSelected_iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBI2T1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KLEBANG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBI2T1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Deployment test/SA/iframe_Stock Adjustment_undefined_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBI2T1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_InventoryAdjustmentDetail1_cbpInventoryAdjustmentDetails_ASPxRoundPanel1_formInventoryAdjustment_cbWarehouse_cbWarehouse_DDD_L_LBT']/tr[3]/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLEBANG'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BERCHAM RAYA'])[2]/following::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST18'])[1]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST18'])[2]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tr[3]/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
