<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cash Purchase_undefined (1)</name>
   <tag></tag>
   <elementGuidId>4cb44abd-dc72-4627-ba26-f1b2db4c53b7</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>CloseJqueryLoadingPanel();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Modules/Purchase/m_CashPurchaseDetail.aspx?EncData=hh4V/dtWy8+u8UQ1SFS2D7js/zQCLZrxj09331PvshS4ps8pFmR7O2XuBb9O7WBrCGmulX1M7+TUC8YuZ1TfnF2Ht5T2zbKntuMqI+HzUmNQ3UgqEUpT8OhZi6UsqX1+lQoE1f64I5qGI/c+FeqasNTiYJnPvXZ/dO4M5XUyWVYT74/8nfz+v7cfEqKCP8R5l8O3zb4yW85gtAVqF7LDIw8e28pNlcw+N40tK6nroKs=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>1de551242718314ad9f428095b77144a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='undefined']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabframe_177']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'undefined' and @id = 'undefined' and @src = '/Modules/Purchase/m_CashPurchaseDetail.aspx?EncData=hh4V/dtWy8+u8UQ1SFS2D7js/zQCLZrxj09331PvshS4ps8pFmR7O2XuBb9O7WBrCGmulX1M7+TUC8YuZ1TfnF2Ht5T2zbKntuMqI+HzUmNQ3UgqEUpT8OhZi6UsqX1+lQoE1f64I5qGI/c+FeqasNTiYJnPvXZ/dO4M5XUyWVYT74/8nfz+v7cfEqKCP8R5l8O3zb4yW85gtAVqF7LDIw8e28pNlcw+N40tK6nroKs=']</value>
   </webElementXpaths>
</WebElementEntity>
